#based on economy.yml
all:
  x: 0
  y: 0
  width:  825
  height:  1125

heading:
  x: 100
  y: 90
  width: 630
  height: 120
  align: center
  font_size: 12

player:
  extends: heading
  x: 100
  y: += 140
  height: 60
  align: center

extrabox:
  extends: heading
  x: 100
  y: 310
  height: 165
  width: 630   

icon:
  extends: heading
  x: +=10
  y: 320
  width: 36
  height: 36
  
extra:
  extends: heading
  x: += 90
  y: 330
  width: 530
  height: 145
  align: left
  font_size: 8

title:
  x: 90
  y: 510
  width: 635
  height: 50
  align: center
  font size: 12
  color: "blue"

description:
  extends: heading
  y: += 500
  height: 500
  font_size: 6
  align: left
  font_size: 8

type:
  x: 90
  y: 955
  width: 645
  height: 50
  align: center

lower_right:
  x: 675
  y: 975
  width: 55
  height: 55
  font_size: 6
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 85
  y: 985
  width: 55
  height: 55
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3
