#based on economy.yml
all:
  x: 0
  y: 0
  width:  825
  height:  1125

title:
  x: 90
  y: 90
  width: 635
  height: 50
  align: center

art:
  x: 110
  y: 160
  width: 630
  height: 390
  align: center
  width: :scale

description:
  x: 100
  y: 555
  width: 625
  height: 390
  align: left
  font_size: 6
desc: # alias
  extends: description

type:
  x: 90
  y: 955
  width: 645
  height: 50
  align: center

lower_right:
  x: 685
  y: 985
  width: 55
  height: 55
  font_size: 6
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 85
  y: 985
  width: 55
  height: 55
  font_size: 6
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3
